// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-market-snapshot.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/binance.ts
var BINANCE = "https://api.binance.com";
function toPair(symbol) {
  const raw = symbol.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!raw) throw new Error("symbol is required");
  return /(USDT|USDC|BUSD|BTC|ETH)$/.test(raw) ? raw : `${raw}USDT`;
}
async function binanceGet(path, params) {
  const url = new URL(`${BINANCE}${path}`);
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, String(v));
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 1e4);
  try {
    const res = await fetch(url.toString(), {
      headers: { accept: "application/json" },
      signal: controller.signal
    });
    if (!res.ok) {
      throw new Error(`Binance ${path} failed (${res.status}) \u2014 the pair may not be listed`);
    }
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

// src/lib/mcp/tools/get-market-snapshot.ts
var get_market_snapshot_default = defineTool({
  name: "get_market_snapshot",
  title: "Get market snapshot",
  description: "Live 24h price snapshot for a crypto asset (price, % change, high/low, volume) sourced from Binance spot markets.",
  inputSchema: {
    symbol: z.string().describe("Asset or pair, e.g. 'BTC', 'SOL' or 'BTCUSDT'. Defaults to USDT quote.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ symbol }) => {
    const pair = toPair(symbol);
    const t = await binanceGet("/api/v3/ticker/24hr", { symbol: pair });
    const snapshot = {
      pair: t.symbol,
      price: Number(t.lastPrice),
      change_24h_pct: Number(t.priceChangePercent),
      high_24h: Number(t.highPrice),
      low_24h: Number(t.lowPrice),
      volume_24h_base: Number(t.volume),
      volume_24h_usd: Number(t.quoteVolume),
      as_of: (/* @__PURE__ */ new Date()).toISOString()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(snapshot) }],
      structuredContent: snapshot
    };
  }
});

// src/lib/mcp/tools/get-whale-trades.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_whale_trades_default = defineTool2({
  name: "get_whale_trades",
  title: "Get whale trades",
  description: "Recent large ('whale') trades for an asset: aggregated Binance trades filtered by a minimum USD notional, newest first.",
  inputSchema: {
    symbol: z2.string().describe("Asset or pair, e.g. 'BTC' or 'BTCUSDT'."),
    min_usd: z2.number().optional().describe("Minimum trade size in USD. Default 100000."),
    limit: z2.number().optional().describe("Max trades to return, 1-50. Default 20.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ symbol, min_usd, limit }) => {
    const pair = toPair(symbol);
    const minUsd = Number.isFinite(min_usd) && min_usd > 0 ? min_usd : 1e5;
    const max = Math.min(Math.max(Math.trunc(limit ?? 20) || 20, 1), 50);
    const raw = await binanceGet("/api/v3/aggTrades", { symbol: pair, limit: 1e3 });
    const trades = raw.map((t) => {
      const price = Number(t.p);
      const qty = Number(t.q);
      return {
        trade_id: String(t.a),
        asset: pair,
        price,
        quantity: qty,
        amount_usd: Math.round(price * qty),
        transaction_type: t.m ? "sell" : "buy",
        timestamp: new Date(t.T).toISOString()
      };
    }).filter((t) => t.amount_usd >= minUsd).sort((a, b) => a.timestamp < b.timestamp ? 1 : -1).slice(0, max);
    const payload = { pair, min_usd: minUsd, count: trades.length, trades };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-orderbook-pressure.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_orderbook_pressure_default = defineTool3({
  name: "get_orderbook_pressure",
  title: "Get order book pressure",
  description: "Live order book imbalance for an asset: total bid vs ask liquidity near the spread and the resulting buy/sell pressure bias.",
  inputSchema: {
    symbol: z3.string().describe("Asset or pair, e.g. 'ETH' or 'ETHUSDT'."),
    depth: z3.number().optional().describe("Number of book levels per side, 5-100. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ symbol, depth }) => {
    const pair = toPair(symbol);
    const levels = Math.min(Math.max(Math.trunc(depth ?? 50) || 50, 5), 100);
    const book = await binanceGet("/api/v3/depth", { symbol: pair, limit: 100 });
    const sum = (rows) => rows.slice(0, levels).reduce((acc, [p, q]) => acc + Number(p) * Number(q), 0);
    const bidUsd = sum(book.bids);
    const askUsd = sum(book.asks);
    const total = bidUsd + askUsd;
    const imbalance = total > 0 ? (bidUsd - askUsd) / total : 0;
    const payload = {
      pair,
      levels,
      bid_liquidity_usd: Math.round(bidUsd),
      ask_liquidity_usd: Math.round(askUsd),
      imbalance: Number(imbalance.toFixed(4)),
      bias: imbalance > 0.1 ? "buy_pressure" : imbalance < -0.1 ? "sell_pressure" : "balanced",
      best_bid: Number(book.bids[0]?.[0] ?? 0),
      best_ask: Number(book.asks[0]?.[0] ?? 0),
      as_of: (/* @__PURE__ */ new Date()).toISOString()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-council-decisions.ts
import { defineTool as defineTool4, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-council-decisions.ts
var list_council_decisions_default = defineTool4({
  name: "list_council_decisions",
  title: "List AI council decisions",
  description: "Recent verdicts from this app's multi-agent AI trading council (bull/bear/risk/trader/PM), newest first. Optionally filter by asset symbol.",
  inputSchema: {
    symbol: z4.string().optional().describe("Filter by asset symbol, e.g. 'BTC'."),
    limit: z4.number().optional().describe("Max decisions to return, 1-25. Default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol, limit }) => {
    const max = Math.min(Math.max(Math.trunc(limit ?? 10) || 10, 1), 25);
    let query = supabaseAnon().from("council_decisions").select("id,symbol,depth,final_verdict,conviction,price_at,reflection,created_at").order("created_at", { ascending: false }).limit(max);
    if (symbol?.trim()) {
      query = query.ilike("symbol", `%${symbol.trim()}%`);
    }
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    const payload = { count: data?.length ?? 0, decisions: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "crypto-whale-tracker-pro",
  title: "CRYPTO Whale Tracker Pro",
  version: "0.1.0",
  instructions: "Live crypto market intelligence from Whale Radar. Use `get_market_snapshot` for 24h price stats, `get_whale_trades` for recent large-notional trades, `get_orderbook_pressure` for bid/ask imbalance, and `list_council_decisions` for the app's AI trading-council verdicts. All data is public and read-only.",
  tools: [get_market_snapshot_default, get_whale_trades_default, get_orderbook_pressure_default, list_council_decisions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
